print("Single Arrow")
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *****")
print()
print("Doubled Arrow")
print("        *")
print("       * *")
print("      *   *")
print("     *     *")
print("    *       *")
print("   *         *")
print("  *           *")
print(" *             *")
print("*****       *****")
print("    *       *")
print("    *       *")
print("    *       *")
print("    *       *")
print("    *       *")
print("    *********")
print()
print("Duplicated Arrows")
print("        *         " * 2)
print("       * *        " * 2)
print("      *   *       " * 2)
print("     *     *      " * 2)
print("    *       *     " * 2)
print("   *         *    " * 2)
print("  *           *   " * 2)
print(" *             *  " * 2)
print("*****       ***** " * 2)
print("    *       *     " * 2)
print("    *       *     " * 2)
print("    *       *     " * 2)
print("    *       *     " * 2)
print("    *       *     " * 2)
print("    *********     " * 2)